name: Release

on:
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  NODE_VERSION: 24

jobs:
  changesets:
    name: Process Changesets
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          commit: "[ci] release packages"
          title: "(CI) Release Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release:
    name: Release
    needs: [changesets]
    if: needs.changesets.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Configure Build Environment
        uses: ./.github/actions/configure-build-env
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: ./tools/scripts/publish-docker.sh